site_name: GTdownloader
site_url: https://example.com/

nav:
    - Home: index.md
    - Getting started: sections/start.md
    - User guide:
        - API keys: sections/credentials.md
        - Downloading tweets: sections/download.md
        - Exports: sections/export.md
        - Plotting: sections/plot.md
    - About: sections/about.md
    - Reference: sections/reference.md

theme: readthedocs

plugins:
- search
- mkdocstrings:
    handlers:
        python:
            selection:
                docstring_style: numpy
            rendering:
                docstring_section_style: table
                heading_level: 2
                show_root_heading: true
                show_submodules: false


